sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: my450rzES+jFtKUP/zQpGWoK+4azYiUNHw2nrPhDTpHl0ZUFVEr4IwC6NZe/KJQj8zFSaTjq32bhLURLiKpK9rsqwru8DFwJUM/99Fg0UDRe5kTuF6h6aSUVXP2U3PeGzYbBbEBxvZnUkeohqi6T4CVzFp04OGpD+tCMRETvbBCxqeRXdrw3stUStd3rts6muqdkJ8T77705o077MDFVw5/sOixJKEAOzj3cGjPfVwAvZKDM481sjPBit6InciX7LwrGlrjuYrt/Ut8XuTX96HErvPl1d0+rqmds58oUd2XywAyCpa6WR8r3X2UsLW3Vr+z7DQqZCFzTW7hYlW4o9eMZEBmeWnYgkbQxruwwOIUMGtKVi2lY6/bQ91O//gOBYnML+xLNyaBQa6dxwRIfjd6wgCeHkrwP9y5cB/aOFfrGTGPMKWqG3CZWZl5Dt8+kvts48AVEbliLp6TzYcbrJ+adWfoTXyGbzUIAumNm8ZH3E2Oe9yK6MAIOxSg4PW7yoO3PMr8XsXLZvyEIa6Ln70z3R4vS54GbixjJ7D4vHsiAMy2rSlHjlqmbl7goToM0rCSZG191m4rYMbsAfdYSiCrVO41CptTXX3ae5gFixc6yGAGg1tOBsSHtg57qUYj3e37ektUWZH5p/7yQlIrjsmuz6JENADU46gptlKkqjaA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Serge-Panine---Complete_3918
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy